### ISSUE TITLE
When set opt_certinfo: 1, Sometimes get error

### ISSUE THREAD

**Issue by Madongming** [pawadski/curlhttp_exporter#2]
curl "http://localhost:10080/?target=https://github.com/"
```
Error while handling error: not enough values to unpack (expected 2, got 1)
Stack: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 766, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "./exporter.py", line 139, in error_handler
    raise exception
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 750, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "./exporter.py", line 164, in print_request
    return sanic.response.text(data.result())
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./exporter.py", line 131, in handleRequest
    stats = getStats(c)
  File "./exporter.py", line 84, in getStats
    output_stats['certinfo'] = getSslInfo(handler)
  File "./exporter.py", line 64, in getSslInfo
    key, value = entry.split(' = ')
ValueError: not enough values to unpack (expected 2, got 1)
```
And I'm debug the entry:
```
===========businessCategory = Private Organization===================
===========jurisdictionC = US===================
===========jurisdictionST = Delaware===================
===========serialNumber = 5157550===================
===========C = US===================
===========ST = California===================
===========L = San Francisco===================
===========O = "GitHub===================
===========Inc."===================
```

so :
add these code:
```
def getSslInfo(handler):
    explode = ['subject', 'issuer']        # to sort into a sub-dict
    dates = ['start_date', 'expire_date']
    strings = ['version', 'signature', 'public key algorithm', 'serial number', 'signature algorithm']

    certStats = []
    for certificate in handler.getinfo(pycurl.INFO_CERTINFO):
        cert = { 'metrics': {}, 'labels': {} }
        for item in certificate:
            attribute = item[0].replace(' ', '_').lower()

            if attribute in explode:
                for entry in item[1].split(', '):
--------here--------------------------
                    if len(entry) != 2:
                        continue
---------------------------------------
                    key, value = entry.split(' = ')
                    cert['labels'][ f"{attribute}_{key.lower()}" ] = value
                # cert[item[0]] = dict( k.split('=') for k in item[1].split(', ') )
                continue
```
It's work!

**Comment by pawadski** [comment]
Thank you. It seems like some systems/openssl libraries report SSL keys slightly different, so the split sometimes panics. I have added some changes very recently, from the devel branch, to help mitigate this. Can you test the latest **master** to see if this is still a problem?

Does it happen when you use the Docker container as well?
