### ISSUE TITLE
curlhttp_exporter throws error during probing

### ISSUE THREAD

**Issue by eozcany** [pawadski/curlhttp_exporter#5]
I have tried to run it on Cnetos7 
All the necessary python mudles are installed.
It is tarting normally but cannot probe endpoint and throws error while trying to open metrics on browser.

Exception happened during processing of request from ('10.127.26.4', 46774)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "curlhttp_exporter.py", line 27, in __init__
    super(RequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "curlhttp_exporter.py", line 206, in do_GET
    metrics = self.probe_go(target)
  File "curlhttp_exporter.py", line 122, in probe_go
    self.set_curl_options(curl_handle)
  File "curlhttp_exporter.py", line 42, in set_curl_options
    curl_handle.setopt(attr, value)
pycurl.error: (48, '')

**Comment by eozcany** [comment]
Even pycurl has been installed withour any issue

# pip3.6 install pycurl
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Requirement already satisfied: pycurl in /usr/local/lib64/python3.6/site-packages

**Comment by eozcany** [comment]
What can be the reason that I cannot use it.

**Comment by pawadski** [comment]
Thanks for opening the issue, can you share the following:
1. The exporter config
2. The usage (ie. how you query it)
3. If you can use Docker, does the problem exist when using the Docker image?

CURLE_UNKNOWN_OPTION (48)

An option passed to libcurl is not recognized/known. Refer to the appropriate documentation. This is most likely a problem in the program that uses libcurl. The error buffer might contain more specific information about which exact option it concerns.

**Comment by eozcany** [comment]
Hello, Thanks for your reply
1. Exporter config is same with github repository, I just changed the port
to 9116
2. python3.6 exporter.py
3. No, I need to run it in EC2 instance.

Thanks for your all assistance

**Comment by pawadski** [comment]
Thanks. I was able to reproduce this on a brand new install with latest versions of the modules. It appears that the latest version of PyYAML may not be compatible, but version 3.13 is working! I will add it to the README.

Also, you may need to ensure that your libcurl and pycurl is built on top of openssl and not nss (which seems to be the default on CentOS 7) to use the SSL reporting functionality. The Docker image is provided to go around these hurdles.

BTW, you should be able to install Docker Community Edition on the EC2 instance. Then run the exporter like:

```
git clone https://github.com/pawadski/curlhttp_exporter.git
cd curlhttp_exporter
bash build-run
```

I will try to find the time to bring this up to latest PyYAML (hopefully) over the weekend.

**Comment by eozcany** [comment]
Hello,
Thank you for your all assistances.

I will follow your suggestions ans let you know.

Best Regards.

27 Mar 2020 Cum 18:36 tarihinde pawadski <notifications@github.com> şunu
yazdı:

**Comment by pawadski** [comment]
@eozcany I have narrowed it down to an old libcurl version in CentOS 7. I get `libcurl-7.29.0-54.el7_7.2.x86_64` when I install `libcurl` in CentOS 7 (fresh install). My dev system has `libcurl-7.69.1-1.1.cf.rhel7.x86_64` I believe from the CityFan repository (http://www.city-fan.org/ftp/contrib/yum-repo/). So I don't think the version of PyYAML matters.

It appears the old CentOS 7 libcurl version does not support OPT_CERTINFO, so the init step fails. :(

**Comment by pawadski** [comment]
For the time being I am setting this to `wontfix` as this is not in fact a code problem, but a dependency problem. I will update the readme with this information on next push, hopefully happening within the next couple days.

**Comment by pawadski** [comment]
Pushed commit 5abdf72a856556e904be20dbbaf029379e4cffc0 with more information in readme and some code changes.
